lidar:
    driver:
      lidar_type: RS16           #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /rslidar           #Frame id of message
      msop_port: 6691              #Msop port of lidar
      difop_port: 7781             #Difop port of lidar
      device_ip: 192.168.1.201
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
    motor:
      port: /dev/ttyUSB0
      baudrate: 115200
      nums: 2
      id: 1
      dir: /home/ubuntu/lidar/1/


